In [1]:
import tensorflow as tf
import numpy as np
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
from pylab import rcParams
rcParams['figure.figsize'] = 20, 6

In [90]:
'''
Truth
'''
nClasses = 3
pVec = np.array([0.3,0.6,0.1])
y = np.random.multinomial(1,pVec,10)
classWeights = 1.0/y.sum(0)
print(y)
print(classWeights)
y = tf.constant(y,dtype="float64")
classWeights = tf.constant(classWeights,"float64")

[[0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]]
[ 0.33333333  0.16666667  1.        ]


In [91]:
'''
Pred
'''
pVecPred = np.array([0.2,0.5,0.3])
n = 100.0
yPred = np.random.multinomial(n,pVecPred,10)/n
print(yPred)
yPred = tf.constant(yPred)
ce = -tf.log(yPred)*y
wce = ce*classWeights
ace = tf.reduce_mean(tf.reduce_sum(ce,1))
awce = tf.reduce_mean(tf.reduce_sum(wce,1))
#ceL = tf.nn.softmax_cross_entropy_with_logits(tf.log(yPred),y)

[[ 0.13  0.6   0.27]
 [ 0.19  0.56  0.25]
 [ 0.15  0.58  0.27]
 [ 0.21  0.54  0.25]
 [ 0.23  0.42  0.35]
 [ 0.18  0.55  0.27]
 [ 0.12  0.55  0.33]
 [ 0.24  0.45  0.31]
 [ 0.22  0.52  0.26]
 [ 0.15  0.59  0.26]]


In [92]:
with tf.Session() as sess:
    loss,weightedLoss,cw = sess.run([ce,wce,classWeights])
    print(cw)
    print("*"*35)
    print(loss)
    print("*"*35)
    print(weightedLoss)

[ 0.33333333  0.16666667  1.        ]
***********************************
[[ 0.          0.51082562  0.        ]
 [ 0.          0.5798185   0.        ]
 [ 0.          0.54472718  0.        ]
 [ 0.          0.          1.38629436]
 [ 1.46967597  0.          0.        ]
 [ 0.          0.597837    0.        ]
 [ 0.          0.597837    0.        ]
 [ 0.          0.7985077   0.        ]
 [ 1.51412773  0.          0.        ]
 [ 1.89711998  0.          0.        ]]
***********************************
[[ 0.          0.0851376   0.        ]
 [ 0.          0.09663642  0.        ]
 [ 0.          0.09078786  0.        ]
 [ 0.          0.          1.38629436]
 [ 0.48989199  0.          0.        ]
 [ 0.          0.0996395   0.        ]
 [ 0.          0.0996395   0.        ]
 [ 0.          0.13308462  0.        ]
 [ 0.50470924  0.          0.        ]
 [ 0.63237333  0.          0.        ]]
